### ISSUE TITLE
build broken (Nr 339)

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42#128]

**Comment by gernotstarke** [comment]
it is Build-Nr 339, not issue-Nr

**Comment by gernotstarke** [comment]
puh - an issue:
* bump gradle and gradle-wrapper version
* correct output paths in build.gradle (images dir not within html5 dir

**Comment by aheusingfeld** [comment]
regarding https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development/README.adoc, we will probably also need to distinguish betweet "options" and "attributes" in the plugin configuration.

I couldn't find the gradle version the plugin claims to be compatible with, did you see it?

**Comment by gernotstarke** [comment]
I’ll bump gradle to V 2.x, and will restructure build.gradle to comply to asciidoctor-gradle-plugin 1.5.2 (remove our own copyImages task)…

imho no need to add attributes - options seem to be enough.

thx for caring :-)
Gernot

 
> Am 14.02.2015 um 09:06 schrieb Alexander Heusingfeld <notifications@github.com>:
> 
> regarding https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development/README.adoc <https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/development/README.adoc>, we will probably also need to distinguish betweet "options" and "attributes" in the plugin configuration.
> 
> I couldn't find the gradle version the plugin claims to be compatible with, did you see it?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/aim42/aim42/issues/128#issuecomment-74366436>.
> 

Dr. Gernot Starke

---
Willi-Lauf Allee 43, D-50858 Köln
gs@gernotstarke.de <mailto:gs@gernotstarke.de>,
+49 177 - 728 2570
http://www.gernotstarke.de <http://www.gernotstarke.de/>

 <http://www.gernotstarke.de/>Twitter: @gernotstarke

****************************************
Das freie Portal für Software-Architekten:
http://www.arc42.de <http://www.arc42.de/>

**Comment by aheusingfeld** [comment]
:+1:

about the "attributes":
The section backwards compatibility says nested attributes in "options" is deprecated but still supported for now. That's why I mentioned it. ;)

**Comment by gernotstarke** [comment]
build now works find locally - but Travis still complains:

FAILURE: Build failed with an exception.

* Where:

Build file '/home/travis/build/aim42/aim42/publish.gradle' line: 14

    * What went wrong:

    A problem occurred evaluating root project 'aim42'.

    > Failed to apply plugin [id 'github-pages']

    > Could not find method add() for arguments [cleanGhPages, class org.gradle.api.tasks.Delete] on task set.

Tried to bump up plugin version to 1.0.0 - let's commit, push and see :-)

**Comment by gernotstarke** [comment]
looks better now.. at least travis-ci console output shows "green build". Will close this one...
