### ISSUE TITLE
review overview (phase) diagram

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42#135]
crosscutting should be included...

**Comment by gernotstarke** [comment]
![aim42-phases](https://cloud.githubusercontent.com/assets/1233990/6327561/a1b87edc-bb5d-11e4-8c46-77c0b76cdbd1.jpg)

**Comment by gernotstarke** [comment]
![aim42-phases](https://cloud.githubusercontent.com/assets/1233990/6327570/c52d112a-bb5d-11e4-9317-a79aed5b3822.png)

**Comment by gernotstarke** [comment]
@lilienth - thanx for your suggestion.

Will include it in the book-chapter too.

**Comment by lilienth** [comment]
+1
