### ISSUE TITLE
define "domain model" for improvement

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42#151]
containing:

* issue
* improvement-opportunity
* risk
* system information

and appropriate attributes and relations

(@Hruschka has some ideas for this)

**Comment by gernotstarke** [comment]
start with graffle diagram

**Comment by gernotstarke** [comment]
![aim42-domain-model](https://cloud.githubusercontent.com/assets/1233990/6547731/06b270ee-c5e1-11e4-98f2-1dc747448642.png)

**Comment by gernotstarke** [comment]
Further ideas (@Hruschka, please comment):
* goals and constraints
* is "Documentation" covering "System information"

**Comment by aheusingfeld** [comment]
My 2 cents:
- Software also "consists-of" "configuration"
- I don't think we can say that "Stakeholder _is source_ of issue" in general
- A "System" also has "configuration", "lifecycle" and hopefully a "purpose" or at least a "business case" ;)
- I'd say that a "System _serves a_/ _supports_ process"
- "Organization" has "principles" and "structure" ... which both are often the "source of issue" :)

Typos in the diagram:
- Improvement resolve_s_ Issue (singular) 
- Issue _is_ resolved by Improvement (singular)
- Risk has an "EaryWarning"?

BTW: I like the "1..*" relation stating that if an improvement does not resolve an issue it is not an improvement! Nice statement!

**Comment by gernotstarke** [comment]
> Am 09.03.2015 um 01:22 schrieb Alexander Heusingfeld <notifications@github.com>:
> 
> My 2 cents:
> 
> Software also "consists-of" „configuration“
yep - included that. 
> I don't think we can say that "Stakeholder is source of issue" in general
imho we can: Via developers, admins, architects, managers you learn about issues (durring Stakeholder-Interviews).
You’re right - they are not the only source of issues!!

We might include a second relation between System and Issue, labelled: „found by analyzing"
> A "System" also has "configuration", "lifecycle" and hopefully a "purpose" or at least a "business case" ;)
config: see above, done. „Lifecycle"
> I'd say that a "System serves a/ supports process“
relation between System and Process has *many* meanings: e.g. developed, managed, operated, supported etc.
did not want to name all I can think of, will try in textual/tabular description! 
> "Organization" has "principles" and "structure" ... which both are often the "source of issue" :)
right - but we don’t want to focus on organizational stuff here. Will include „goals and constraints“
in Domain-Model - we already introduced those in Analyze recently as artifact.
> Typos in the diagram:
> 
> Improvement resolve_s_ Issue (singular)
no, deliberately not: one improvement might resolve several issues
> Issue is resolved by Improvement (singular)
see above, might be several
> Risk has an "EaryWarning“?
in DE: Frühwarnsignal, a 
> BTW: I like the "1..*" relation stating that if an improvement does not resolve an issue it is not an improvement! Nice statement!
> 


thanx Alex - great ideas!!

Gernot

**Comment by aheusingfeld** [comment]
> > I don't think we can say that "Stakeholder is source of issue" in general

> imho we can: Via developers, admins, architects, managers you learn about issues (durring Stakeholder-Interviews).

Wouldn't that better have a "Stakeholder _informs about_/ _knows about_ issue"?

**Comment by gernotstarke** [comment]
current version looks like that:
![aim42-domain-model](https://cloud.githubusercontent.com/assets/1233990/6551443/f201b30a-c638-11e4-949c-ebc273baf038.png)

**Comment by gernotstarke** [comment]
current version looks like that:
![aim42-domain-model](https://cloud.githubusercontent.com/assets/1233990/6557027/3b2eaa22-c672-11e4-8593-96584ac9cf48.png)
