### ISSUE TITLE
remove logo from TOC

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42#182]
just a minor glitch: logo currently appears twice when opening aim42.github.io - which looks strange.

solution approach: remove from level-1 heading,
or try to remove the "method guide" heading from TOC

**Comment by gernotstarke** [comment]
tried different approaches, does not work.
Will accept logo in header and TOC... sigh

**Comment by rschimmack** [comment]
Hi Gernot,
please have a look at my patch for removing the logo from the TOC. Is the rendering Ok for you?

**Comment by gernotstarke** [comment]
exactly how I envisioned it - thanx!!
