### ISSUE TITLE
table "evaluation domain concepts" is broken

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42#192]
third column contains "TOC" instead of text...
(I remember that was an asciidoctor issues some time ago...)

**Comment by rschimmack** [comment]
Hi Gernot,

this is a side effect of commit "bumped to gradle 2.13, aim-version 0.7". Here version of asciidoctor-gradle-plugin was changed from 1.5.2 - 1.5.3. Unfortunately  asciidoctor-gradle-plugin 1.5.3 has a bug relating to TOC in table (see issue #177 of asciidoctor/asciidoctor-gradle-plugin).

Cheers 
Roland
