### ISSUE TITLE
Clarify integration with ITIL CSI

### ISSUE THREAD

**Issue by aheusingfeld** [aim42/aim42#204]
If an organization based their processes on ITIL, aim42 should clarify in which way it integrates with ITIL - e.g. the Continual Service Improvement part - and where aim42 has a different approach.

http://wiki.en.it-processmaps.com/index.php/ITIL_CSI_-_Continual_Service_Improvement

**Comment by gernotstarke** [comment]
good idea - imho this could be the topic of an article or presentation - and does not neccessarily need to be included in the aim42 reference.

**Comment by gernotstarke** [comment]
I'll close this one - imho too far off topic of the core aim42 approach.
