### ISSUE TITLE
extract asciidoc howto

### ISSUE THREAD

**Issue by MichaelMahlberg** [aim42/aim42#205]
Include currently used non-standard links etc. in how to

**Comment by gernotstarke** [comment]
Michael - are you working on that issues?

**Comment by gernotstarke** [comment]
imho we should extract the asciidoc hints to their own document, as they don't belong to the core of aim42.

Another repo seems overkill - so maybe https://github.com/arc42/HHGDAC is a good place (see "Folge-4" in that repo for a starting point)

**Comment by gernotstarke** [comment]
removed from the method reference - moved issue to aim42.org website
