### ISSUE TITLE
decide on color-schema

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42#211]
proposal: 

orange/reddish = analyze, find issues
yellow = evaluate
blue/green = improve

**Comment by gernotstarke** [comment]
![aim42-colors-proposed](https://cloud.githubusercontent.com/assets/1233990/26024335/a395b83c-37cf-11e7-9ca1-be5573b0336a.png)

**Comment by gernotstarke** [comment]
[aim Colours shootout.pdf](https://github.com/aim42/aim42/files/998495/aim.Colours.shootout.pdf)

**Comment by barthel** [comment]
Have you checked these colors with someone who suffers on a dyschromatopsia (red-green visual weakness)?
Btw. I like this color schema.

**Comment by gernotstarke** [comment]
no, didn't... (no expert on these topics around the project).

**Comment by gernotstarke** [comment]
btw - updated version:
<img width="340" alt="grafik" src="https://cloud.githubusercontent.com/assets/1233990/26025988/260b9b92-37f3-11e7-86bc-1751af57a5f6.png">

**Comment by barthel** [comment]
I'm not a expert too.
Maybe it would help to check the color scheme with:
  http://www.color-blindness.com/coblis1-color-blindness-simulator/

**Comment by gernotstarke** [comment]
oops - it does not work well - at least for some of the CB-categories.  
I found a color-set which should work:

http://mkweb.bcgsc.ca/colorblind/img/colorblindness.palettes.trivial.pdf

I'll give that one a try

**Comment by gernotstarke** [comment]
<img width="341" alt="grafik" src="https://cloud.githubusercontent.com/assets/1233990/26026464/f9d8e79c-37fb-11e7-9212-806cfa69f697.png">

This color-scheme passed the CB-test

**Comment by barthel** [comment]
The difference between the colors of ``analyze`` and ``improve`` is not big enough for the Monochromacy.
But the most CB-views are pretty well, I think.

Thanks for supporting this awareness.

**Comment by gernotstarke** [comment]
Well, thanx for pointing this issue out to me.

In case you have additional ideas for contributions… I’ll most happily make you a committer here :-)

best regards, Gernot

**Comment by barthel** [comment]
I'm currently looking to find a good starting point for contribution. ;-)
My english language skills are far away to write articles in english and I'm not an artist to re-paint drawings or diagrams.

**Comment by gernotstarke** [comment]
reviews, opinion, proposals…

we’re currently working on „accessibility“ - making the whole stuff easier to understand, hopefully creating simpler access
and better overview.

provide experience reports of all kinds concerning system improvement, modernization, evolution. Horror stories welcome.

ok?

**Comment by gernotstarke** [comment]
Conclusion: We'll go for the color-blind-aware scheme here. 

It's available online at:
https://coolors.co/d55e00-f0e442-0072b2-009e73-50514f

**Comment by aheusingfeld** [comment]
I absolutely favor considering color-blindness, but does that really exclude bright colors? The above palette looks like a rainy day in March. :-/

If we want to go for new colors, I'd rather have something warm, bright, welcoming. I will ask Mona or Sonja for some advice, if you don't veto.

**Comment by gernotstarke** [comment]
do we talk about the same colors? "rainy day in March"... sounds devastating to  me...
No, I don't veto - but: reddish and greenish is a must - yellowish and blueish might be replaced by something else.
Originally I had https://coolors.co/f6511d-ffb400-2c9cc0-7fb800-50514f in mind, but that does not work for CB people...

**Comment by gernotstarke** [comment]
![fd0023-45db86-4ca9fc-d0fd23-c707f7](https://cloud.githubusercontent.com/assets/1233990/26234958/708bb4a8-3c68-11e7-8b87-2d5108c31851.png)

**Comment by gernotstarke** [comment]
another proposal by a UX guy... wh

**Comment by barthel** [comment]
I like the colors of "rainy day in march" and does not associating these with a rainy day.

What do you think about a bit 'stronger' colors like:
![cb3027-f58d34-0c50a1-56585b-1b6010](https://cloud.githubusercontent.com/assets/1170328/26235827/8a604402-3c6d-11e7-8dd0-bc43debf6916.png)

**Comment by barthel** [comment]
Maybe a bit brighter?

![1c9044-d00000-ffba08-a2aebb-3f88c5](https://cloud.githubusercontent.com/assets/1170328/26236028/9794d330-3c6e-11e7-9389-3e6385b4b175.png)

**Comment by gernotstarke** [comment]
I asked several of the aim42 committers and some (IT-aware) friends of mine for their opinion on our color proposals...

Most were (intensely) in favor of the schema contributed by Falk (see above).

I decided to take that one for now - as we should concentrate mainly on content...

@barthel: thanx for your contributions!
