### ISSUE TITLE
Add "intro graphics"

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42#213]
to give an overview.

An (enhanced) version of this "info graphic" might serve as an overall navigation

**Comment by gernotstarke** [comment]
<img width="1411" alt="grafik" src="https://cloud.githubusercontent.com/assets/1233990/26067377/4e7da798-399a-11e7-8f2f-44f6e3c44264.png">

**Comment by aheusingfeld** [comment]
I like the overall idea of that circle made of 3 arrows which circulate around the crosscutting concerns. Regarding the content let's do a hard one: 
1. let's come up with suggestions for the 3 most important Words (or 2-word-terms) in each section
2. Vote which ones are most important
3. Take the top 5 ;) of each section and put them on the graphic

**Comment by aheusingfeld** [comment]
BTW: I think I love the idea of having icons in there! If we manage to have them in and still not too much content to overwhelm readers, it'd be awesome!

**Comment by gernotstarke** [comment]
I'm lacking ideas what (else) to  include in "evaluate". One idea: add "check the success of improvements" (our fundamental principle: validate improvement, turned into a practice)

The other "keywords" in the circle are ok, imho, at least until we come up with better proposals.

**Comment by aheusingfeld** [comment]
Ok, here is my first take

analyze
- find issues
- collect improvements
- separate both
- make them measurable

evaluate
- calculate issue cost
- estimate improvement effort
- ingest interval estimation 

improve
- improve value
- prioritize by impact

crosscutting
- issue-improvement-relations
- common constraints
- perpetual principles

**Comment by gernotstarke** [comment]
thanx Alex - I propose: slight modifications in wording, move some entries... 

### analyze

* understand system
* find issues
* collect improvement options
    
### evaluate

* estimate issue cost
* estimate improvement effort
* estimate in intervals

### improve

* improve value
* improve quality

### crosscutting

* manage issue-improvement relations
* plan improvements
* handle constraints

**Comment by MichaelMahlberg** [comment]
Without looking at the diagram or the previous answer (but looking at the guide itself):
### Analyze
* Inspect System
* Collect Issues
* Inspect Environment

### Evaluate
* Financial model
* Implications (Kano-Model,  
* Trade-Offs

### Improve
* Modify system
* Modify Environment
* Iterate

### Crosscutting
* Plan
* Negotiate
* Verify

Ceterum Censeo: 
As I said before: There are more things to consider for "evaluate" than we currently consider:

Here are a few things to consider:
* build financial model 
* determine cost of delay
* determine NPV
* balance alternatives
* quantify risk

And yes, those can all b summarized under "calculate cost", but that is akin to summarizing all improvements under "make system better"

**Comment by MichaelMahlberg** [comment]
I actually like @gernotstarke's current list best, I just would not go with "estimate in intervals" because to me that is on a different level of abstraction. (And it is not about _what_ to do, but _how_ to do it)

I would suggest "build financial model" but that is more than two words...

**Comment by gernotstarke** [comment]
Slightly simplified the version from my first comment, re-colored according to brighter color schema:

![aim42-intro-recolored](https://cloud.githubusercontent.com/assets/1233990/26285565/b4396a74-3e52-11e7-9e54-0ac191856e7b.png)

**Comment by gernotstarke** [comment]
included this image here: http://aim42.org/apply/getting-started/
