### ISSUE TITLE
SSL certificate problem (name mismatch) on https://aim42.org

### ISSUE THREAD

**Issue by jachstet-sea** [aim42/aim42#223]
Since the website is hosted (and uses the SSL certificate by) github, there is a certificate name mismatch when browsing to https://aim42.org
See: https://www.ssllabs.com/ssltest/analyze.html?d=aim42.org
Possibly related to #147

**Comment by gernotstarke** [comment]
Sorry, https://aim42.org is currently not supported.

Please use http://aim42.org instead.
