### ISSUE TITLE
enable https on aim42.org website

### ISSUE THREAD

**Issue by gernotstarke** [aim42/aim42#228]
possibly with cloudflare:
https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

alternate description:
https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html

**Comment by aheusingfeld** [comment]
Shouldn‘t that actually be located in https://github.com/aim42/aim42.org-site/issues ?

**Comment by gernotstarke** [comment]
Right you are - our reference manual doesn't need https...
