### ISSUE TITLE
Broken Link Improve Process in chapter 4.5.

### ISSUE THREAD

**Issue by claudioaltamura** [aim42/aim42#237]
I discovered that in chapter 4.5 "Categories of Improvement Practices" the link to "Improve Process" doesn't work: http://aim42.github.io/#mprove-processes

"i" is missing in improve. Correct is http://aim42.github.io/#improve-processes .

**Comment by aheusingfeld** [comment]
Thanks a lot for bringing this up. Should be fixed with the next build.
