### ISSUE TITLE
Is there an ePub version for consumption on mobile?

### ISSUE THREAD

**Issue by dmitrym0** [aim42/aim42#238]
Since the output of the build process is HTML it should be possible to wrap it up in an ePub envelope. Unfortunately I"m not familiar with the build ecosystem used so I don't know how to generate the HTML. 

What should I do to generate an HTML page or alternatively is there an ePUB already?

**Comment by gernotstarke** [comment]
Dmitry, currently we don't generate an epub version - but in principle the asciidoc build allows for other output formats. 

We'll have a look - but it may take a while, though...

regards, Gernot

**Comment by dmitrym0** [comment]
Is it possible to generate a single page html document?

**Comment by aheusingfeld** [comment]
Actually aim42.github.io _is_ a single html page, isn’t it?

**Comment by dmitrym0** [comment]
@aheusingfeld you're absolutely correct. I assumed that there was some iframe magic. In any case
here's an epub https://www.dropbox.com/s/jih6mjzokp8drfx/aim42-november-17-2017.epub alternatively you can feed the aim42 url to [this service](https://ebook.online-convert.com/convert-to-epub) and it will produce the epub.
