### ISSUE TITLE
Capture Quality Requirements - broken link

### ISSUE THREAD

**Issue by koepalex** [aim42/aim42#239]
The link to the Real-world examples of software quality requirements (which will be moved to github under arc42) is currently broken:

https://bitbucket.org/arc42/quality-requirements Results in 404 Page of bit bucket

**Comment by gernotstarke** [comment]
oops - it has long been moved to Github - I'll check and correct asap (but not today - as StarWars movie start is keeping me from my computer this evening)

**Comment by gernotstarke** [comment]
the correct link is https://github.com/arc42/quality-requirements

I'll update that on aim42 asap

**Comment by aheusingfeld** [comment]
Thanks @koepalex, I fixed both links
