### ISSUE TITLE
fix presentation of links in Method Reference

### ISSUE THREAD

**Issue by pirad** [aim42/aim42#244]
When I open http://aim42.github.io/#_how_it_works the text is 

> Improve your Section 5.5 of the [System] by Section 2.3.3

and so on. It seems the links are not shown as they should as the regarding section 5.5 has a name that fits good into the text.
Expected behaviour is
> Improve your [Architectural-Understanding] of the [System] by [Context-Analysis]

Shown version is 0.7.7. Given Date is Mar 1, 2018. Browsers tested: Firefox 58 on Ubuntu and Chrome for Android 65.

**Comment by gernotstarke** [comment]
oops - that's a problem with asciidoc link/reference configuration...

I'll look into that - may take a few days. Thanx for raising that issue!

**Comment by gernotstarke** [comment]
fixed by configuring :xrefstyle: full (in file "index.adoc")

**Comment by pirad** [comment]
Now it shows 

>Improve your Section 5.5, “Architectural-Understanding” of the [System] by
Section 2.3.3, “Context-Analysis”

It would be easier to read without the "section X.x" in between.
According to https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/xrefstyle.adoc 
The style basic is what I mean.

**Comment by gernotstarke** [comment]
I see your point.

Let us briefly discuss that with a handful of other committers:

@MichaelMahlberg @vanto @svenjohann @aheusingfeld - what's your opinion?

**Comment by pirad** [comment]
All I'm saying is that the current version is sometimes confusing, because the text is written as if the Section part should be ignored.
> For every entry in this issue list we need to Section 3.3.3, “Estimate Issue Cost”

**Comment by pirad** [comment]
All I'm saying is that the current version is sometimes confusing, because the text is written as if the Section part should be ignored.
> For every entry in this issue list we need to Section 3.3.3, “Estimate Issue Cost”
